---
- name: Load overlay and br_netfilter modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter
  tags: kernel_modules

- name: Make kernel modules persistent at boot
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    src: modules-load-d-k8s.conf
    mode: 0644
    owner: root
    group: root

- name: Set net.ipv4.ip_forward to 1 
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: yes
    reload: true
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward
  tags: k8s_sysctl