all:

  hosts:
    gitlab:
      ansible_host: gitlab.superuser.kz
      ansible_become: true
      ansible_user: ubuntu

  children:
    dev_kubernetes:
      children:
        controlplane:
          hosts:
            control1:
              ansible_host: control1.dev.superuser.kz
              internal-ip: 192.168.0.111
            control2:
              ansible_host: control2.dev.superuser.kz
              internal-ip: 192.168.0.112
            control3:
              ansible_host: control3.dev.superuser.kz
              internal-ip: 192.168.0.113
        workers:
          hosts:
            worker1:
              ansible_host: worker1.dev.superuser.kz
              internal-ip: 192.168.0.121
            worker2:
              ansible_host: worker2.dev.superuser.kz
              internal-ip: 192.168.0.122
            worker3:
              ansible_host: worker3.dev.superuser.kz
              internal-ip: 192.168.0.123
      vars:
        ansible_ssh_common_args: "-J ubuntu@gitlab.superuser.kz"
        ansible_become: true
        ansible_user: ubuntu